In [1]:
import numpy as np

In [2]:
arr1=np.array([])

In [3]:
type (arr1)

numpy.ndarray

In [4]:
my_list=[1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [5]:
a=np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [7]:
my_list+[2,3]

[1, 2, 3, 4, 5, 2, 3]

In [8]:
a.ndim

1

In [9]:
a.size

5

In [10]:
a.shape

(5,)

In [11]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix
type(my_matrix)

list

In [12]:
b=np.array(my_matrix)

In [13]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
type(b)

numpy.ndarray

In [15]:
b.ndim

2

In [16]:
b.size

12

In [17]:
b.shape

(3, 4)

In [18]:
arr1=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr1.shape

(2, 2, 3)

In [20]:
arr1.ndim

3

In [21]:
arr1[1][1][1]

np.int64(11)

In [22]:
arr1[0][0][1]

np.int64(2)

In [23]:
np.mean([1,2,3,45])

np.float64(12.75)

In [24]:
l1=[1,2,3,45]

In [25]:
import pandas as pd 
l1=[1,2,3,45]
d1=pd.DataFrame(l1)
d1.mean()

0    12.75
dtype: float64

# reshape function

In [26]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr2.shape

(1, 4, 3)

In [29]:
arr2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
desc_arr=np.sort(arr2.reshape(-1))[::-1]
desc_arr

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## arange

In [31]:
list(range(10+1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
np.arange(5,50)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

## zeros and ones

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [36]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [38]:
np.ones((2,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# linspace

In [39]:
import numpy as np

In [40]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [41]:
np.linspace(5,25,10,retstep=True)

(array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
        16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ]),
 np.float64(2.2222222222222223))

In [42]:
np.linspace(0,25,retstep=True)

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 np.float64(0.5102040816326531))

In [43]:
np.linspace(0,200,10)#default retstep =false

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [44]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 np.float64(22.22222222222222))

# eye

In [45]:
import numpy as np

In [46]:
np.eye(7)#diagonal nums 1 rest of zero

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# broadcasting in an array

In [47]:
big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
big_one.dtype

dtype('float64')

In [49]:
type(big_one)

numpy.ndarray

In [50]:
big_one*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [51]:
bigger_one=big_one*6 -2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [52]:
big_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
bigger=np.array(big_one*5 -3, dtype="int")
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [54]:
bigger.dtype

dtype('int64')

In [55]:
type(bigger)

numpy.ndarray

In [56]:
bigger.shape

(3, 4)

In [57]:
bigger//bigger

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [58]:
bigger

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [59]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
1/arr1[1:]

array([[[0.14285714, 0.125     , 0.11111111],
        [0.1       , 0.09090909, 0.08333333]]])

In [61]:
1/arr1[0:]

array([[[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]],

       [[0.14285714, 0.125     , 0.11111111],
        [0.1       , 0.09090909, 0.08333333]]])

In [62]:
import warnings
warnings.filterwarnings("ignore")

In [63]:
arr1=np.arange(20)
1/arr1

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [64]:
arr=np.arange(4)

In [65]:
arr

array([0, 1, 2, 3])

In [66]:
arr+arr

array([0, 2, 4, 6])

In [67]:
arr**arr

array([ 1,  1,  4, 27])

# use of copy function

In [68]:
arr1=np.arange(0,19)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [69]:
arr1[7]=100

In [70]:
arr1

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [71]:
arr1

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [72]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr2=arr1
arr2

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [74]:
arr1[2]=100

In [75]:
arr1

array([  0,   1, 100,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [76]:
arr2

array([  0,   1, 100,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [77]:
array=np.arange(21)

In [78]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [79]:
arr3=arr1.copy()

In [80]:
arr3

array([  0,   1, 100,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

In [81]:
print(arr3)
print(arr1)

[  0   1 100   3   4   5   6 100   8   9  10  11  12  13  14  15  16  17
  18]
[  0   1 100   3   4   5   6 100   8   9  10  11  12  13  14  15  16  17
  18]


In [82]:
arr3[10:]=100

In [83]:
arr3

array([  0,   1, 100,   3,   4,   5,   6, 100,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100])

In [84]:
arr1 # copy function retains the original..copy creates a backup array

array([  0,   1, 100,   3,   4,   5,   6, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18])

# random number generation

In [85]:
np.random.rand()

0.3021746335285451

In [86]:
np.random.rand(10)

array([0.3690608 , 0.08221557, 0.06347048, 0.6471802 , 0.6725392 ,
       0.43561883, 0.13147126, 0.37658346, 0.25293649, 0.1759341 ])

In [87]:
np.random.rand(5,2)

array([[0.16611109, 0.10682663],
       [0.95230877, 0.92782185],
       [0.4346313 , 0.02502037],
       [0.45199163, 0.83680272],
       [0.65008321, 0.57117626]])

In [88]:
new_arr=np.random.rand(5,3)
#2D array of shape(5,3)

In [89]:
arr1=np.random.randn(50)# normally distributed
arr1

array([ 0.00781072, -0.40257706, -0.01998077, -0.69773321, -0.78815997,
        0.06406642,  0.14136759,  2.52495454,  0.60585809, -0.2890031 ,
        0.06357086, -0.94817516,  0.85826132, -1.19928817,  0.93332018,
        0.01780781, -0.15981224,  0.65694502, -0.24385908,  0.0508573 ,
       -0.23530725, -0.14852944,  0.54711871, -0.76914262,  1.53366372,
       -0.38798796, -1.44897528,  0.09086532, -0.9362213 ,  2.07930151,
        0.6923364 ,  0.48808465, -1.47845181,  0.93831679,  1.42259065,
       -0.40875964,  0.9752007 , -0.75364201, -0.56085299, -0.34734758,
        0.94518021,  0.63674122, -1.4723654 , -1.38819712, -1.57277389,
        0.63706913,  0.61686664, -1.50981043,  0.12995831, -0.19663729])

In [90]:
np.mean(arr1)

np.float64(-0.014109539095561896)

In [91]:
np.median(arr1)

np.float64(-0.006085024246144634)

In [92]:
np.std(arr1)

np.float64(0.9195186813964186)

# randint

In [93]:
np.random.randint(1,100)

67

In [94]:
np.random.randint(1,7)

6

# min ,max ,aggmin,aggmax

In [95]:
arr2=np.random.randint(1,100,20)

In [96]:
arr2

array([83, 12, 19, 31, 54, 43, 52, 67, 96,  6, 48, 71, 90, 44, 37,  1, 35,
       72, 71, 81], dtype=int32)

In [97]:
arr2.max()

np.int32(96)

In [98]:
arr2.min()

np.int32(1)

In [99]:
arr2.argmin()

np.int64(15)

In [100]:
arr2.argmax()

np.int64(8)

In [101]:
ranarr=np.random.randint(0,100,10)
ranarr

array([12, 46, 73, 52, 96,  0, 57, 45,  7, 54], dtype=int32)

In [102]:
ranarr.max()

np.int32(96)

In [103]:
ranarr.argmax()

np.int64(4)

In [104]:
ranarr.min()

np.int32(0)

In [105]:
ranarr.argmin()

np.int64(5)

In [106]:
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [107]:
len(arr)

18

In [108]:
arr[9]

np.int64(55)

In [109]:
arr[1:11:2]

array([15, 25, 35, 45, 55])

In [110]:
arr[-1]

np.int64(95)

# filtering

In [111]:
arr=np.array([1,2,1010,4,108,18,71,610])

In [112]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [113]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [114]:
np.where(arr>100)

(array([2, 4, 7]),)

In [115]:
arr[5]

np.int64(18)

In [116]:
arr[2]

np.int64(1010)

In [117]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [118]:
np.where(arr<100)

(array([0, 1, 3, 5, 6]),)

In [119]:
arr[np.where(arr>100)]

array([1010,  108,  610])

In [120]:
arr[np.where(arr<100)]

array([ 1,  2,  4, 18, 71])

In [121]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [122]:
arr_2d=np.array(([1,2,3],[12,15,18],[64,96,128]))
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [123]:
arr_2d[2,1]

np.int64(96)

In [124]:
l1=[1,2,3,4,5]

In [125]:
arr3=np.arange(27).reshape(3,3,3)

In [126]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [129]:
arr4=np.arange(15).reshape(3,5)

In [130]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
arr4[1:,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [132]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [133]:
arr_2d[1]

array([12, 15, 18])

In [135]:
arr5=np.arange(20).reshape(5,4)

In [136]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [137]:
arr5[1:4,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])